### ISSUE TITLE
General Installation Instructions

### ISSUE THREAD

**Issue by juliangaal** [juliangaal/python-cheat-sheet#2]
The bigger this repo gets, the more sense it makes to add Python installation instructions, Atom optimisation for Python and/or a short mention of Anaconda to `README.md`

If you want to help me out with this, feel free to do so and fork this repo or contact me [here](twitter.com/JulianGaal). Thanks

**Comment by Nifled** [comment]
I think this is kinda late, but I can help out and add the installation guide.

**Comment by juliangaal** [comment]
Sure. I appreciate any help, I'll have a look at it once you're ready

**Comment by Nifled** [comment]
It's ready, you can check out my PR. Also made additional changes. Thanks.

**Comment by juliangaal** [comment]
Thanks, again. Really exceeded my expectations ;)

**Comment by Nifled** [comment]
No problem! I think you can close this issue for now.
