### ISSUE TITLE
Table of content broken after conversion to pdf

### ISSUE THREAD

**Issue by juliangaal** [juliangaal/python-cheat-sheet#6]
I am using the `markdown-pdf` package to convert `.md` into `.pdf` via [Atom](https://atom.io/packages/markdown-pdf). However, it seems the toc and it's automatic forwarding on click breaks during the process. </br> Any ideas how to solve this?

EDIT: would pandoc work for this? Anyone has experience with it?

**Comment by karelin** [comment]
Personally, I prefer RST (reStructuredText, standard *de facto* for Python documentation), for preparing things like you do here. See http://www.sphinx-doc.org/ for details.

It is converted to PDF via LaTeX, a bit involved but usually quire stable.

Existing `.md` can be converted to `.rst` using `pandoc`.

Side note: your link to [atom.io](http://atom.io) points to nowhere.

**Comment by JulianGaal** [comment]
link corrected.

Will take a look at RST, thanks!

**Comment by juliangaal** [comment]
Fixed with "markdown-preview-enhanced"-package for Atom
